### ISSUE TITLE
Including custom fiscal year overwrites existing values

### ISSUE THREAD

**Issue by dschach** [SalesforceLabs/ProjectManagementTool#1]
force-app/main/default/settings/Company.settings-meta.xml

Perhaps delete this file from the repository so that it doesn't interfere with customers' existing orgs. I don't think it affects the package's performance... does it?

There's already a company setting for fiscal year. Why is there also a Custom Metadata Type for the same thing? Maybe just let the app run based on the org setting? If it will break everything if the company changes its fiscal year, then maybe the app needs some ways to handle that.

**Comment by shekhargawali** [comment]
@dschach , the company settings have been removed from the code and will not overwrite the settings anymore.
About using the custom metadata, it gives more flexibility in formula fields and validations.
