### ISSUE TITLE
GanntView Progress bar won't change color

### ISSUE THREAD

**Issue by amounie** [SalesforceLabs/ProjectManagementTool#11]
Hello,
I just installed PMT and everything seems to be going fine and I'm getting ready to push it to my production org but I'm having an issue in the Gannt view: 
There is no visual indication of the status of the project: ex. the progress bar doesn't seem to change color or display the health icon.
While this isn't blocking it kind of defeats the purpose of Project Management if you can't see the status of the projects. So I am wondering if the lack of color change in the progress bar is by design of if it's a bug ?

As an additional question has someone figured out a way to show the status of the projects/tasks/phase in an other way ?

Thanks

**Comment by shekhargawali** [comment]
@amounie , it is a design choice. The updated gantt now adds legends for each color and what it represents. Also, included the health icon on the gantt chart.
