### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Englhard** [SalesforceLabs/ProjectManagementTool#3]
Hello, I can't install the package at all.  I get the following install error when trying to install.

1. (PMT_Project__c-PMT Project Page Layout FY20-Q1) The ActionId specified was invalid for ActionType QuickAction.
PMT_Project__c-PMT Project Page Layout FY20-Q1: The ActionId specified was invalid for ActionType QuickAction.

**Comment by Englhard** [comment]
@shekhargawali

**Comment by shekhargawali** [comment]
@Englhard , a new patch has been released on appExchange. Can you try to install it again now? Thanks

**Comment by Englhard** [comment]
@shekhargawali That works now, thanks!
