### ISSUE TITLE
I CAN'T INSTALL PMT FOR MY SALESFORCE

### ISSUE THREAD

**Issue by mimikoc** [SalesforceLabs/ProjectManagementTool#7]
It says:
Your request to install package "PMT 1.8 Major Release with Gantt" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.
Error Number: 1781194516-18258 (-1041981071)
WHAT SHOULD I DO CAN YOU PLEASE HELP ME

**Comment by mimikoc** [comment]
@shekhargawali

**Comment by shekhargawali** [comment]
@mimikoc, closing this issue as it looks like an org issue. The package is getting installed in developer edition and other production orgs.
